apiserver:
  image: zrrrzzt/tfk-api-postnummer:latest@sha256:e72c44bd24f5005d684d58abbc8d8bd5904d067916306b1e7dcf717335d415ea
  environment:
    SERVER_PORT: 3000
    DB: mongodb://mongodb_1:27017/tfk
  ports:
      - "3000:3000"
  links:
    - mongodb
mongodb:
  image: mongo:latest@sha256:15adfdd96e1bba9fa6bc6ebe8e9c69cd49b563ec43a6f6dc63eac96f4e63ab00
  environment:
    DB: tfk
    COLLECTION: zipcodes
  ports:
   - "27017:27017"