apiserver:
  image: zrrrzzt/tfk-api-postnummer:latest@sha256:f5de637db920228ce9d095dc51fa1c9bbe31a166661e1eb2e3f9eb5944e54fcd
  environment:
    SERVER_PORT: 3000
    DB: mongodb://mongodb_1:27017/tfk
  ports:
      - "3000:3000"
  links:
    - mongodb
mongodb:
  image: mongo:latest@sha256:15adfdd96e1bba9fa6bc6ebe8e9c69cd49b563ec43a6f6dc63eac96f4e63ab00
  environment:
    DB: tfk
    COLLECTION: zipcodes
  ports:
   - "27017:27017"