apiserver:
  image: zrrrzzt/tfk-api-postnummer:3.0.0
  environment:
    SERVER_PORT: 3000
    DB: mongodb://mongodb_1:27017/tfk
  ports:
      - "3000:3000"
  links:
    - mongodb
mongodb:
  image: mongo:5.0.0
  environment:
    DB: tfk
    COLLECTION: zipcodes
  ports:
   - "27017:27017"