apiserver:
  image: zrrrzzt/tfk-api-postnummer:latest@sha256:c9d90e93c24e6edaf0645e0f85799b4b53eddeaf695bc842d0ca260daae484ad
  environment:
    SERVER_PORT: 3000
    DB: mongodb://mongodb_1:27017/tfk
  ports:
      - "3000:3000"
  links:
    - mongodb
mongodb:
  image: mongo:latest@sha256:3a09cd85fb4e76f1d5832f9ea1d4e7481f76e807389b7d8ea6ac4d4ba96f83e5
  environment:
    DB: tfk
    COLLECTION: zipcodes
  ports:
   - "27017:27017"