apiserver:
  image: zrrrzzt/tfk-api-postnummer:latest@sha256:0ab00fd146110e2ab0754b69f6bc34aee52d73abd613acb1f28c23a50bfa3116
  environment:
    SERVER_PORT: 3000
    DB: mongodb://mongodb_1:27017/tfk
  ports:
      - "3000:3000"
  links:
    - mongodb
mongodb:
  image: mongo:latest@sha256:bc93023d57ff1d0b3dcfb81ee0ce9455c246f2ed5248a7c5a468e9dd44ce7955
  environment:
    DB: tfk
    COLLECTION: zipcodes
  ports:
   - "27017:27017"