apiserver:
  image: zrrrzzt/tfk-api-postnummer:latest@sha256:c9d90e93c24e6edaf0645e0f85799b4b53eddeaf695bc842d0ca260daae484ad
  environment:
    SERVER_PORT: 3000
    DB: mongodb://mongodb_1:27017/tfk
  ports:
      - "3000:3000"
  links:
    - mongodb
mongodb:
  image: mongo:latest@sha256:84f9f4f66809872d952cdc33946d72df6a02e1e8ee00529e5ccdea46dd08a84f
  environment:
    DB: tfk
    COLLECTION: zipcodes
  ports:
   - "27017:27017"