apiserver:
  image: zrrrzzt/tfk-api-postnummer:latest@sha256:eccfc54421d6474caecb646172eaeca52911aacab70dbd5cf92e3ddc57989a68
  environment:
    SERVER_PORT: 3000
    DB: mongodb://mongodb_1:27017/tfk
  ports:
      - "3000:3000"
  links:
    - mongodb
mongodb:
  image: mongo:latest@sha256:3a09cd85fb4e76f1d5832f9ea1d4e7481f76e807389b7d8ea6ac4d4ba96f83e5
  environment:
    DB: tfk
    COLLECTION: zipcodes
  ports:
   - "27017:27017"